### ISSUE TITLE
Clear all existing dropdown options

### ISSUE THREAD

**Issue by badabingbreda** [zackpyle/BBClassDropdown#2]
There's code to clear all dropdown options. It needs to be entered manually, but a button with a prompt (confirm) that goes to the tab url with the `?clear_bb_options` argument would be a nice touch.

When processed, it would look good if you add a admin notice on top instead of letting wp die(); One like "Settings updated!" when you hit the save changes button.

**Comment by zackpyle** [comment]
Being worked on in [branch here](https://github.com/zackpyle/BBClassDropdown/tree/Reset-Plugin-Settings-Feature)

**Comment by zackpyle** [comment]
Completed in PR #15
