### ISSUE TITLE
Updating js

### ISSUE THREAD

**Issue by badabingbreda** [zackpyle/BBClassDropdown#3]
A sidenote on the custom scripts is that they will persist in the browser if they keep the same version number in the code that enqueues them.

Adding a line

`define( 'BBCLASSDROPDOWN_VERSION' , '1.3.4' );`

that you update when you also update the header version, and also enter that as the $version argument for the wp_enqueue_script and wp_enqueue_style methods ensures that when you update the version you also force the plugin to load new (but maybe the same content) versions of the style and script.

**Comment by zackpyle** [comment]
Fixed in #7. Will be closed after merge with main
